### PR TITLE
No more anime

### PR DESCRIPTION
**Pull request by TwistedPrime**
anime

### CODE REVIEW

**Comment by SphericalKat** [comment]
> Is a weeb
> Makes PR to block some random weeb games

**Comment by TwistedPrime** [comment]
Am otaku not weeb ( ͡°ᴥ ͡° ʋ)

**Comment by argraur** [comment]
Petition to ban OP from this organization.

**Comment by raphielscape** [comment]
Bruh no blocking Nutaku Games

**Pull request closed without merging**
