### PR TITLE
Add and Enable Xiaomi Touch Feature for NVT pannel

### PR DESCRIPTION
**Pull request by archit9169**
I am not exactly sure what Xiaomi Touch Feature is but these are all the changes that i copied either from dipper branch or from other Xiaomi devices that have the same touch pannel. I am not sure what it will do either but my guess is it will enable additional settings in game turbo to allow us to modify touch accordingly.

Atleast test this before disregarding it as a complete waste. maybe it will do something maybe it will not. And if it boots then its not doing any damage.

### CODE REVIEW

**Comment by YumeMichi** [comment]
https://github.com/LineageOS/android_device_xiaomi_common/commit/feecb1ae3680beb54d400fe329490077434b5aac
https://github.com/LineageOS/android_device_xiaomi_davinci/commit/1b6a28d90428f4366a301eac776f6e64a68753d6
https://github.com/LineageOS/android_device_xiaomi_sm6150-common/commit/5f1b8f2e3c1919dfe5598393d3232cc70d69081b

**Comment by raphielscape** [comment]
We don't ship Xiaomi's Touch Feature, as we don't ship that Hacky-ducky Game Mode thingy from Xiaomi and we don't ship Touch Feature HAL for FOD (Fingerprint on Display) either.

I'm proposedly going to strip Xiaomi Touch Feature out from all targets as I imported it from `dipper-q-oss` and it ended up unused as-per Disrupt isn't supporting MIUI in the first place.

**Comment by archit9169** [comment]
But this will work right. If this things does work then it might be worth the effort to build my own kernel.

**Comment by raphielscape** [comment]
Well, I don't know if it'll work or not as I stated before that I don't support MIUI and won't use MIUI. There's must be a reason why Xiaomi didn't ship it for beryllium, though.

**Pull request closed without merging**
